import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import GENERATED_STRATEGIES_DIR


def _ema_rsi_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: EMA + RSI Trend Following                              |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    FastEMA       = {p.get('fast_ema', 14)};
input int    SlowEMA       = {p.get('slow_ema', 50)};
input int    RSIPeriod     = {p.get('rsi_period', 14)};
input double RSIBuyLevel   = {p.get('rsi_buy', 55)};
input double RSISellLevel  = {p.get('rsi_sell', 45)};
input int    StopLoss      = {p.get('stop_loss', 300)};
input int    TakeProfit    = {p.get('take_profit', 600)};
input double RiskPercent   = {p.get('risk_percent', 1.0)};

CTrade trade;
int fastEmaHandle, slowEmaHandle, rsiHandle;
double fastEma[], slowEma[], rsiVal[];

int OnInit()
{{
   fastEmaHandle = iMA(_Symbol, PERIOD_CURRENT, FastEMA, 0, MODE_EMA, PRICE_CLOSE);
   slowEmaHandle = iMA(_Symbol, PERIOD_CURRENT, SlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   rsiHandle     = iRSI(_Symbol, PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE);
   if(fastEmaHandle==INVALID_HANDLE||slowEmaHandle==INVALID_HANDLE||rsiHandle==INVALID_HANDLE)
   {{ Print("Failed to create indicator handles"); return INIT_FAILED; }}
   ArraySetAsSeries(fastEma, true);
   ArraySetAsSeries(slowEma, true);
   ArraySetAsSeries(rsiVal,  true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(fastEmaHandle);
   IndicatorRelease(slowEmaHandle);
   IndicatorRelease(rsiHandle);
}}

double CalcLotSize()
{{
   double balance  = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt  = balance * RiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot      = riskAmt / (StopLoss * tickVal / tickSize);
   double minLot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double step     = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(minLot, MathMin(maxLot, lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(fastEmaHandle, 0, 0, 3, fastEma) < 3) return;
   if(CopyBuffer(slowEmaHandle, 0, 0, 3, slowEma) < 3) return;
   if(CopyBuffer(rsiHandle,     0, 0, 3, rsiVal)  < 3) return;
   bool buySignal  = fastEma[1] > slowEma[1] && fastEma[2] <= slowEma[2] && rsiVal[1] > RSIBuyLevel;
   bool sellSignal = fastEma[1] < slowEma[1] && fastEma[2] >= slowEma[2] && rsiVal[1] < RSISellLevel;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(buySignal)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss * pt, ask + TakeProfit * pt);
   if(sellSignal)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss * pt, bid - TakeProfit * pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _breakout_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: ATR Breakout                                           |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    BreakoutPeriod = {p.get('breakout_period', 20)};
input int    ATRPeriod      = {p.get('atr_period', 14)};
input double ATRMultiplier  = {p.get('atr_multiplier', 2.0)};
input int    StopLoss       = {p.get('stop_loss', 300)};
input int    TakeProfit     = {p.get('take_profit', 600)};
input double RiskPercent    = {p.get('risk_percent', 1.0)};

CTrade trade;
int atrHandle;
double atrVal[], highArr[], lowArr[];

int OnInit()
{{
   atrHandle = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   if(atrHandle == INVALID_HANDLE) {{ Print("ATR handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(atrVal,  true);
   ArraySetAsSeries(highArr, true);
   ArraySetAsSeries(lowArr,  true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason) {{ IndicatorRelease(atrHandle); }}

double CalcLotSize()
{{
   double balance  = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt  = balance * RiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot      = riskAmt / (StopLoss * tickVal / tickSize);
   double step     = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(atrHandle, 0, 0, 3, atrVal) < 3) return;
   if(CopyHigh(_Symbol, PERIOD_CURRENT, 1, BreakoutPeriod, highArr) < BreakoutPeriod) return;
   if(CopyLow(_Symbol,  PERIOD_CURRENT, 1, BreakoutPeriod, lowArr)  < BreakoutPeriod) return;
   double highestHigh = highArr[ArrayMaximum(highArr)];
   double lowestLow   = lowArr[ArrayMinimum(lowArr)];
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   if(ask > highestHigh + atrVal[1] * ATRMultiplier * pt)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss * pt, ask + TakeProfit * pt);
   if(bid < lowestLow - atrVal[1] * ATRMultiplier * pt)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss * pt, bid - TakeProfit * pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _bollinger_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: Bollinger Band Mean Reversion                          |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    BBPeriod      = {p.get('bb_period', 20)};
input double BBDeviation   = {p.get('bb_deviation', 2.0)};
input int    RSIPeriod     = {p.get('rsi_period', 14)};
input double RSIOversold   = {p.get('rsi_oversold', 30)};
input double RSIOverbought = {p.get('rsi_overbought', 70)};
input int    StopLoss      = {p.get('stop_loss', 200)};
input int    TakeProfit    = {p.get('take_profit', 400)};
input double RiskPercent   = {p.get('risk_percent', 1.0)};

CTrade trade;
int bbHandle, rsiHandle;
double bbUpper[], bbLower[], bbMiddle[], rsiVal[];

int OnInit()
{{
   bbHandle  = iBands(_Symbol, PERIOD_CURRENT, BBPeriod, 0, BBDeviation, PRICE_CLOSE);
   rsiHandle = iRSI(_Symbol,   PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE);
   if(bbHandle==INVALID_HANDLE||rsiHandle==INVALID_HANDLE) {{ Print("Handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(bbUpper,  true);
   ArraySetAsSeries(bbLower,  true);
   ArraySetAsSeries(bbMiddle, true);
   ArraySetAsSeries(rsiVal,   true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(bbHandle);
   IndicatorRelease(rsiHandle);
}}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(bbHandle,  UPPER_BAND,  0, 3, bbUpper)  < 3) return;
   if(CopyBuffer(bbHandle,  LOWER_BAND,  0, 3, bbLower)  < 3) return;
   if(CopyBuffer(bbHandle,  BASE_LINE,   0, 3, bbMiddle) < 3) return;
   if(CopyBuffer(rsiHandle, 0,           0, 3, rsiVal)   < 3) return;
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   if(ask < bbLower[1] && rsiVal[1] < RSIOversold)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss * pt, bbMiddle[1]);
   if(bid > bbUpper[1] && rsiVal[1] > RSIOverbought)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss * pt, bbMiddle[1]);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _macd_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: MACD Crossover                                         |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    MACDFast      = {p.get('macd_fast', 12)};
input int    MACDSlow      = {p.get('macd_slow', 26)};
input int    MACDSignal    = {p.get('macd_signal', 9)};
input int    RSIPeriod     = {p.get('rsi_period', 14)};
input double RSIFilter     = {p.get('rsi_filter', 50)};
input int    StopLoss      = {p.get('stop_loss', 300)};
input int    TakeProfit    = {p.get('take_profit', 600)};
input double RiskPercent   = {p.get('risk_percent', 1.0)};

CTrade trade;
int macdHandle, rsiHandle;
double macdMain[], macdSignal[], rsiVal[];

int OnInit()
{{
   macdHandle = iMACD(_Symbol, PERIOD_CURRENT, MACDFast, MACDSlow, MACDSignal, PRICE_CLOSE);
   rsiHandle  = iRSI(_Symbol,  PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE);
   if(macdHandle==INVALID_HANDLE||rsiHandle==INVALID_HANDLE) {{ Print("Handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(macdMain,   true);
   ArraySetAsSeries(macdSignal, true);
   ArraySetAsSeries(rsiVal,     true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(macdHandle);
   IndicatorRelease(rsiHandle);
}}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(macdHandle, MAIN_LINE,   0, 3, macdMain)   < 3) return;
   if(CopyBuffer(macdHandle, SIGNAL_LINE, 0, 3, macdSignal) < 3) return;
   if(CopyBuffer(rsiHandle,  0,           0, 3, rsiVal)     < 3) return;
   bool bullCross = macdMain[1] > macdSignal[1] && macdMain[2] <= macdSignal[2];
   bool bearCross = macdMain[1] < macdSignal[1] && macdMain[2] >= macdSignal[2];
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(bullCross && rsiVal[1] > RSIFilter)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss * pt, ask + TakeProfit * pt);
   if(bearCross && rsiVal[1] < RSIFilter)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss * pt, bid - TakeProfit * pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _supertrend_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: Supertrend                                             |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    ATRPeriod     = {p.get('atr_period', 10)};
input double ATRMultiplier = {p.get('atr_multiplier', 3.0)};
input int    EMAFilter     = {p.get('ema_filter', 200)};
input int    StopLoss      = {p.get('stop_loss', 300)};
input int    TakeProfit    = {p.get('take_profit', 700)};
input double RiskPercent   = {p.get('risk_percent', 1.0)};

CTrade trade;
int atrHandle, emaHandle;
double atrVal[], emaVal[], highArr[], lowArr[], closeArr[];

int OnInit()
{{
   atrHandle = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   emaHandle = iMA(_Symbol,  PERIOD_CURRENT, EMAFilter, 0, MODE_EMA, PRICE_CLOSE);
   if(atrHandle==INVALID_HANDLE||emaHandle==INVALID_HANDLE) {{ Print("Handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(atrVal,   true);
   ArraySetAsSeries(emaVal,   true);
   ArraySetAsSeries(highArr,  true);
   ArraySetAsSeries(lowArr,   true);
   ArraySetAsSeries(closeArr, true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(atrHandle);
   IndicatorRelease(emaHandle);
}}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(atrHandle, 0, 0, 3, atrVal)   < 3) return;
   if(CopyBuffer(emaHandle, 0, 0, 3, emaVal)   < 3) return;
   if(CopyHigh(_Symbol, PERIOD_CURRENT, 0, 3, highArr)  < 3) return;
   if(CopyLow(_Symbol,  PERIOD_CURRENT, 0, 3, lowArr)   < 3) return;
   if(CopyClose(_Symbol, PERIOD_CURRENT,0, 3, closeArr) < 3) return;
   double hl2        = (highArr[1] + lowArr[1]) / 2.0;
   double upperBand  = hl2 + ATRMultiplier * atrVal[1];
   double lowerBand  = hl2 - ATRMultiplier * atrVal[1];
   bool upTrend   = closeArr[1] > lowerBand && emaVal[1] > emaVal[2];
   bool downTrend = closeArr[1] < upperBand && emaVal[1] < emaVal[2];
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(upTrend)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss * pt, ask + TakeProfit * pt);
   if(downTrend)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss * pt, bid - TakeProfit * pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _adx_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: ADX Trend Filter + EMA                                 |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    ADXPeriod     = {p.get('adx_period', 14)};
input double ADXThreshold  = {p.get('adx_threshold', 25)};
input int    FastEMA       = {p.get('fast_ema', 12)};
input int    SlowEMA       = {p.get('slow_ema', 50)};
input int    StopLoss      = {p.get('stop_loss', 300)};
input int    TakeProfit    = {p.get('take_profit', 600)};
input double RiskPercent   = {p.get('risk_percent', 1.0)};

CTrade trade;
int adxHandle, fastEmaHandle, slowEmaHandle;
double adxMain[], diPlus[], diMinus[], fastEma[], slowEma[];

int OnInit()
{{
   adxHandle      = iADX(_Symbol, PERIOD_CURRENT, ADXPeriod);
   fastEmaHandle  = iMA(_Symbol,  PERIOD_CURRENT, FastEMA, 0, MODE_EMA, PRICE_CLOSE);
   slowEmaHandle  = iMA(_Symbol,  PERIOD_CURRENT, SlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   if(adxHandle==INVALID_HANDLE||fastEmaHandle==INVALID_HANDLE||slowEmaHandle==INVALID_HANDLE)
   {{ Print("Handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(adxMain,   true);
   ArraySetAsSeries(diPlus,    true);
   ArraySetAsSeries(diMinus,   true);
   ArraySetAsSeries(fastEma,   true);
   ArraySetAsSeries(slowEma,   true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(adxHandle);
   IndicatorRelease(fastEmaHandle);
   IndicatorRelease(slowEmaHandle);
}}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(adxHandle,     MAIN_LINE, 0, 3, adxMain)  < 3) return;
   if(CopyBuffer(adxHandle,     1,         0, 3, diPlus)   < 3) return;
   if(CopyBuffer(adxHandle,     2,         0, 3, diMinus)  < 3) return;
   if(CopyBuffer(fastEmaHandle, 0,         0, 3, fastEma)  < 3) return;
   if(CopyBuffer(slowEmaHandle, 0,         0, 3, slowEma)  < 3) return;
   bool strongTrend = adxMain[1] > ADXThreshold;
   bool bullTrend   = fastEma[1] > slowEma[1] && diPlus[1]  > diMinus[1] && strongTrend;
   bool bearTrend   = fastEma[1] < slowEma[1] && diMinus[1] > diPlus[1]  && strongTrend;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(bullTrend)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss * pt, ask + TakeProfit * pt);
   if(bearTrend)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss * pt, bid - TakeProfit * pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _donchian_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: Donchian Channel Breakout                              |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    DonchianPeriod  = {p.get('donchian_period', 20)};
input int    ATRPeriod       = {p.get('atr_period', 14)};
input int    BreakConfirm    = {p.get('breakout_confirm', 2)};
input int    StopLoss        = {p.get('stop_loss', 300)};
input int    TakeProfit      = {p.get('take_profit', 700)};
input double RiskPercent     = {p.get('risk_percent', 1.0)};

CTrade trade;
int atrHandle;
double atrVal[], highArr[], lowArr[];

int OnInit()
{{
   atrHandle = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   if(atrHandle == INVALID_HANDLE) {{ Print("ATR handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(atrVal,  true);
   ArraySetAsSeries(highArr, true);
   ArraySetAsSeries(lowArr,  true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason) {{ IndicatorRelease(atrHandle); }}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(atrHandle, 0, 1, DonchianPeriod, atrVal) < DonchianPeriod) return;
   if(CopyHigh(_Symbol, PERIOD_CURRENT, 1, DonchianPeriod, highArr) < DonchianPeriod) return;
   if(CopyLow(_Symbol,  PERIOD_CURRENT, 1, DonchianPeriod, lowArr)  < DonchianPeriod) return;
   double chanHigh = highArr[ArrayMaximum(highArr)];
   double chanLow  = lowArr[ArrayMinimum(lowArr)];
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   if(ask > chanHigh) trade.Buy(lot,  _Symbol, ask, ask - StopLoss*pt, ask + TakeProfit*pt);
   if(bid < chanLow)  trade.Sell(lot, _Symbol, bid, bid + StopLoss*pt, bid - TakeProfit*pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _multi_tf_code(name: str, p: dict) -> str:
    higher_tf_map = {"H4": "PERIOD_H4", "D1": "PERIOD_D1", "H1": "PERIOD_H1"}
    higher_period = higher_tf_map.get(p.get("higher_timeframe", "H4"), "PERIOD_H4")
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: Multi-Timeframe EMA + RSI                              |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    FastEMA        = {p.get('fast_ema', 14)};
input int    SlowEMA        = {p.get('slow_ema', 50)};
input int    HigherTFEMA    = {p.get('higher_tf_ema', 100)};
input int    RSIPeriod      = {p.get('rsi_period', 14)};
input double RSIBuyLevel    = {p.get('rsi_buy', 55)};
input double RSISellLevel   = {p.get('rsi_sell', 45)};
input int    StopLoss       = {p.get('stop_loss', 300)};
input int    TakeProfit     = {p.get('take_profit', 700)};
input double RiskPercent    = {p.get('risk_percent', 1.0)};

CTrade trade;
int fastEmaH, slowEmaH, htfEmaH, rsiH;
double fastEma[], slowEma[], htfEma[], rsiVal[];

int OnInit()
{{
   fastEmaH = iMA(_Symbol, PERIOD_CURRENT, FastEMA,     0, MODE_EMA, PRICE_CLOSE);
   slowEmaH = iMA(_Symbol, PERIOD_CURRENT, SlowEMA,     0, MODE_EMA, PRICE_CLOSE);
   htfEmaH  = iMA(_Symbol, {higher_period}, HigherTFEMA, 0, MODE_EMA, PRICE_CLOSE);
   rsiH     = iRSI(_Symbol, PERIOD_CURRENT, RSIPeriod,   PRICE_CLOSE);
   if(fastEmaH==INVALID_HANDLE||slowEmaH==INVALID_HANDLE||htfEmaH==INVALID_HANDLE||rsiH==INVALID_HANDLE)
   {{ Print("Handle failed"); return INIT_FAILED; }}
   ArraySetAsSeries(fastEma, true);
   ArraySetAsSeries(slowEma, true);
   ArraySetAsSeries(htfEma,  true);
   ArraySetAsSeries(rsiVal,  true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(fastEmaH);
   IndicatorRelease(slowEmaH);
   IndicatorRelease(htfEmaH);
   IndicatorRelease(rsiH);
}}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(CopyBuffer(fastEmaH, 0, 0, 3, fastEma) < 3) return;
   if(CopyBuffer(slowEmaH, 0, 0, 3, slowEma) < 3) return;
   if(CopyBuffer(htfEmaH,  0, 0, 3, htfEma)  < 3) return;
   if(CopyBuffer(rsiH,     0, 0, 3, rsiVal)  < 3) return;
   double closeNow = iClose(_Symbol, PERIOD_CURRENT, 1);
   bool htfBull = closeNow > htfEma[1];
   bool htfBear = closeNow < htfEma[1];
   bool buyCond  = htfBull && fastEma[1] > slowEma[1] && fastEma[2] <= slowEma[2] && rsiVal[1] > RSIBuyLevel;
   bool sellCond = htfBear && fastEma[1] < slowEma[1] && fastEma[2] >= slowEma[2] && rsiVal[1] < RSISellLevel;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(buyCond)  trade.Buy(lot,  _Symbol, ask, ask - StopLoss*pt, ask + TakeProfit*pt);
   if(sellCond) trade.Sell(lot, _Symbol, bid, bid + StopLoss*pt, bid - TakeProfit*pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


def _news_avoidance_code(name: str, p: dict) -> str:
    return f"""//+------------------------------------------------------------------+
//| {name}                                                           |
//| Strategy: EMA + RSI with News Avoidance                          |
//| Generated by MedXora AI                                          |
//+------------------------------------------------------------------+
#property copyright "MedXora AI"
#property version   "1.00"
#include <Trade\\Trade.mqh>

input int    FastEMA           = {p.get('fast_ema', 14)};
input int    SlowEMA           = {p.get('slow_ema', 50)};
input int    RSIPeriod         = {p.get('rsi_period', 14)};
input double RSIBuyLevel       = {p.get('rsi_buy', 55)};
input double RSISellLevel      = {p.get('rsi_sell', 45)};
input int    NewsPauseMinutes  = {p.get('news_pause_minutes', 60)};
input bool   AvoidFridayClose  = {str(p.get('avoid_friday_close', True)).lower()};
input int    StopLoss          = {p.get('stop_loss', 300)};
input int    TakeProfit        = {p.get('take_profit', 600)};
input double RiskPercent       = {p.get('risk_percent', 1.0)};

CTrade trade;
int fastEmaHandle, slowEmaHandle, rsiHandle;
double fastEma[], slowEma[], rsiVal[];

bool IsNewsTime()
{{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   int minuteOfDay = dt.hour * 60 + dt.min;
   // Avoid major news windows: 8:30, 13:30, 15:00 UTC +-pause
   int news1 = 8*60+30, news2 = 13*60+30, news3 = 15*60;
   if(MathAbs(minuteOfDay - news1) <= NewsPauseMinutes) return true;
   if(MathAbs(minuteOfDay - news2) <= NewsPauseMinutes) return true;
   if(MathAbs(minuteOfDay - news3) <= NewsPauseMinutes) return true;
   if(AvoidFridayClose && dt.day_of_week == 5 && dt.hour >= 20) return true;
   return false;
}}

int OnInit()
{{
   fastEmaHandle = iMA(_Symbol, PERIOD_CURRENT, FastEMA, 0, MODE_EMA, PRICE_CLOSE);
   slowEmaHandle = iMA(_Symbol, PERIOD_CURRENT, SlowEMA, 0, MODE_EMA, PRICE_CLOSE);
   rsiHandle     = iRSI(_Symbol, PERIOD_CURRENT, RSIPeriod, PRICE_CLOSE);
   if(fastEmaHandle==INVALID_HANDLE||slowEmaHandle==INVALID_HANDLE||rsiHandle==INVALID_HANDLE)
   {{ Print("Failed to create handles"); return INIT_FAILED; }}
   ArraySetAsSeries(fastEma, true);
   ArraySetAsSeries(slowEma, true);
   ArraySetAsSeries(rsiVal,  true);
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
   IndicatorRelease(fastEmaHandle);
   IndicatorRelease(slowEmaHandle);
   IndicatorRelease(rsiHandle);
}}

double CalcLotSize()
{{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt = balance * RiskPercent / 100.0;
   double tickVal = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize= SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lot     = riskAmt / (StopLoss * tickVal / tickSize);
   double step    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return MathMax(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX), lot));
}}

void OnTick()
{{
   if(!IsNewBar()) return;
   if(IsNewsTime()) return;
   if(CopyBuffer(fastEmaHandle, 0, 0, 3, fastEma) < 3) return;
   if(CopyBuffer(slowEmaHandle, 0, 0, 3, slowEma) < 3) return;
   if(CopyBuffer(rsiHandle,     0, 0, 3, rsiVal)  < 3) return;
   bool buySignal  = fastEma[1] > slowEma[1] && fastEma[2] <= slowEma[2] && rsiVal[1] > RSIBuyLevel;
   bool sellSignal = fastEma[1] < slowEma[1] && fastEma[2] >= slowEma[2] && rsiVal[1] < RSISellLevel;
   if(PositionsTotal() > 0) return;
   double lot = CalcLotSize();
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double pt  = _Point;
   if(buySignal)
      trade.Buy(lot, _Symbol, ask, ask - StopLoss*pt, ask + TakeProfit*pt);
   if(sellSignal)
      trade.Sell(lot, _Symbol, bid, bid + StopLoss*pt, bid - TakeProfit*pt);
}}

bool IsNewBar()
{{
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBar != lastBar) {{ lastBar = currentBar; return true; }}
   return false;
}}
"""


_CODE_GENERATORS = {
    "ema_rsi":                 _ema_rsi_code,
    "breakout":                _breakout_code,
    "bollinger_mean_reversion":_bollinger_code,
    "macd_crossover":          _macd_code,
    "supertrend":              _supertrend_code,
    "adx_trend_filter":        _adx_code,
    "donchian_breakout":       _donchian_code,
    "multi_tf_ema_rsi":        _multi_tf_code,
    "news_avoidance":          _news_avoidance_code,
}


def generate_mql5(strategy: dict) -> str:
    p            = strategy["parameters"]
    name         = strategy["name"]
    stype        = strategy.get("strategy_type", "ema_rsi")
    generator_fn = _CODE_GENERATORS.get(stype, _ema_rsi_code)
    code         = generator_fn(name, p)
    file_path    = os.path.join(GENERATED_STRATEGIES_DIR, f"{name}.mq5")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(code)
    return file_path


def save_mql5_file(strategy: dict) -> str:
    return generate_mql5(strategy)
